"""add github metadata columns

Revision ID: a816c518b85b
Revises: 21ab2b54790f
Create Date: 2025-12-15 01:19:11.998159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a816c518b85b'
down_revision: Union[str, Sequence[str], None] = '21ab2b54790f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('stars', sa.Integer(), nullable=False))
    op.add_column('repositories', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'language')
    op.drop_column('repositories', 'stars')
    op.drop_column('repositories', 'description')
    # ### end Alembic commands ###
