"""empty message

Revision ID: b821f820423a
Revises: 7d7f8fe04481
Create Date: 2025-12-14 14:18:27.403820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b821f820423a'
down_revision: Union[str, Sequence[str], None] = '7d7f8fe04481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
